(asdf:defsystem "cl-tpg"
  :description "A Common Lisp implementation of Tangled Program Graphs"
  :version "0.4"
  :author "Bryce MacInnis"
  :license "GPL-3"
  :depends-on ("usocket" "alexandria" "bordeaux-threads" "lparallel"
               "py4cl2")
  :components ((:file "package")
	       (:file "helpers")
	       (:file "globals")
	       (:file "agreement")
	       (:file "instruction")
	       (:file "program")
	       (:file "action")
	       (:file "controller")
	       (:file "heuristic")
	       (:file "learner")
	       (:file "team")
	       (:file "effective-code")
		   (:file "checkpoint")
		   (:file "validation")
	       (:file "mutation")
	       (:file "dataset")
	       (:file "hamming")
	       (:file "behavioral-locality")
	       (:file "behavioral-locality-analysis")
	       (:file "migration")
	       (:file "networking")
	       (:file "gym")
	       (:file "teacher")
	       (:file "rare-failure-diagnostics")
	       (:file "policy-disagreement-analysis")
	       (:file "counterfactual-credit")
	       (:file "official-guided")
	       (:file "official-return-credit")
	       (:file "near-miss-lineages")
	       (:file "targeted-repair")
	       (:file "teacher-directed-repair")
	       (:file "teacher-guided-predicate")
	       (:file "incumbent-conservative-repair")
	       (:file "decoy-priority-intervention")
	       (:file "compression-reseed")
	       (:file "main")))
